### PR TITLE
Feature fix animations

### LINKED ISSUE #96: Add transitions between pages

### PR DESCRIPTION
**Pull request by conalli**
## Description

added very basic opacity transition between pages

## Closes issue(s)

Closes #96 

## Screenshots

page-transitions-1

## Changes include

- [x] New feature (non-breaking change that adds functionality)

## Checklist

- [x] I have tested this code

### CODE REVIEW

File: src/pages/About/index.tsx [hunk 1]
```diff
@@ -39,6 +46,6 @@ export const About = () => {
         <SignIn />
       )}
       {/* { {!userData && <SignIn /> }} */}
```
Comment (daiHash) [inline src/pages/About/index.tsx:48]: Could you remove this code? 🙏

**Review by daiHash — APPROVED** [review]
NIce LGTM🙏
